default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: salama-pay-api_development

test:
  <<: *default
  database: salama-pay-api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: salama-pay-api_production
  username: salama-pay-api
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>